services:
  postgres-test:
    image: postgres:15-alpine
    container_name: kwik-postgres-test
    restart: "no"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kwik_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kwik_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c max_connections=200

volumes:
  postgres_test_data:
    driver: local