import setuptools

setuptools.setup(
    name="kwik",
    version="0.0.1",
    author="Davide Mezzogori",
    author_email="davide@mezzogori.com",
    description="The quickest RestAPI backend library",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
    install_requires=[
        "aiofiles",
        "alembic",
        "arrow",
        "asyncpg",
        "bcrypt",
        "broadcaster",
        "celery",
        "emails",
        "fastapi",
        "httptools",
        "jupyter",
        "passlib",
        "psycopg2-binary",
        "pydantic[email]",
        "python-jose",
        "python-multipart",
        "SQLAlchemy",
        "tenacity",
        "uvicorn",
        "websockets",
        "xlsxwriter",
        "pytest",
        "reportlab",
        "pandas",
        "xlrd",
        "openpyxl",
    ],
)
